controller_list:
  - name: fake_Arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_a
      - joint_b
      - joint_c
      - joint_d
      - joint_e
  - name: fake_Hand_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses per group
  - group: Arm
    pose: Home