general:
  camera_model:               'zed2i'
  camera_name:                'zed2i'

depth:
  min_depth:                  0.3             # Min: 0.2, Max: 3.0 - Default 0.7 - Note: reducing this value wil require more computational power and GPU memory
  max_depth:                  20.0            # Max: 40.0
  quality:                    3               # '0': NONE, '1': PERFORMANCE, '2': QUALITY, '3': ULTRA, '4': NEURAL

pos_tracking:
  imu_fusion:                 true            # enable/disable IMU fusion. When set to false, only the optical odometry will be used.

sensors:
  sensors_timestamp_sync:     false           # Synchronize Sensors messages timestamp with latest received frame
  max_pub_rate:               200.            # max frequency of publishing of sensors data. MAX: 400. - MIN: grab rate
  publish_imu_tf:             true            # publish `IMU -> <cam_name>_left_camera_frame` TF
