- name: Wired Connection
  become: True
  nmcli:
    conn_name: MRover
    state: present
    type: ethernet
    ifname: eth0
    autoconnect: yes
    ip4: 10.0.0.10/24
    gw4: 10.0.0.2
    dns4: [10.0.0.2]
    method6: disabled
