- name: Download CUDA Keyring
  get_url:
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.1-1_all.deb
    dest: /tmp/cuda-keyring_1.1-1_all.deb

- name: Install CUDA Keyring
  become: true
  apt:
    deb: /tmp/cuda-keyring_1.1-1_all.deb

- name: Install APT Packages
  become: True
  apt:
    cache_valid_time: 604800
    state: latest
    name:
      - cuda
      - zstd # Required to unpack ZED installer

- name: ZED SDK Download
  get_url:
    url: https://download.stereolabs.com/zedsdk/4.0/cu121/ubuntu20
    dest: /tmp/ZED_SDK_Ubuntu20_cuda12.1_v4.0.7.zstd.run
    mode: 0755

- name: ZED SDK Install
  # Silent mode prevents any user input prompting
  command: /tmp/ZED_SDK_Ubuntu20_cuda12.1_v4.0.7.zstd.run -- silent
  args:
    creates: /usr/local/zed
