- name: Add CMake Key
  apt_key:
    url: https://apt.kitware.com/keys/kitware-archive-latest.asc
    keyring: /usr/share/keyrings/kitware-archive-keyring.gpg

- name: Add CMake APT
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ {{ ubuntu_release }} main
    filename: kitware

- name: Add LLVM Key
  apt_key:
    url: https://apt.llvm.org/llvm-snapshot.gpg.key

- name: Add LLVM APT
  apt_repository:
    repo: deb http://apt.llvm.org/{{ ubuntu_release }}/ llvm-toolchain-{{ ubuntu_release }}-16 main
    filename: llvm

- name: ROS Key
  apt_key:
    url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc
    keyring: /usr/share/keyrings/ros-keyring.gpg

- name: ROS APT
  apt_repository:
    repo: deb http://packages.ros.org/ros/ubuntu {{ ubuntu_release }} main
    filename: ros

- name: Install APT Packages
  apt:
    update_cache: true
    state: latest
    name:
      - zsh
      - neovim
      - sudo
      - cmake
      - ccache
      - tmux
      - zstd
      - python3-pip
      - python3-catkin-tools
      - clang-16
      - clangd-16
      - lld-16
      - lldb-16

- name: Install Catkin Profiles
  synchronize:
    src: files/profiles
    dest: "{{ catkin_workspace }}/.catkin_tools"
    recursive: true
  