- name: Oh-My-Zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: /home/{{ ansible_user_id }}/.oh-my-zsh
    version: master

- name: Dotfiles
  synchronize:
    src: files/home/mrover
    dest: /home
    recursive: true

- name: Use ZSH as a default shell
  become: true
  command: chsh --shell /usr/bin/zsh {{ ansible_user_id }}
