gps_driver:
  port: "/dev/gps"
  baud: 115200
  useRMC: false # get covariance instead of velocity, see wiki for more info
  frame_id: "base_link"

imu_driver:
  port: "/dev/imu"
  baud: 115200
  frame_id: "imu_link"

brushed_motors:
  controllers:
    - name: "cache"
      driver_voltage: 12.0
      motor_max_voltage: 12.0
      mcu_id: 2
      motor_id: 2
      inversion: 1.0
      limit_a_present: true
      limit_b_present: false
      counts_limit_a: 0
      limit_a_is_fwd: true
      calibration_vel: 0.25
    - name: "carousel"
      driver_voltage: 12.0
      motor_max_voltage: 12.0
      mcu_id: 2
      motor_id: 1
      inversion: 1.0
      limit_a_present: true
      limit_b_present: false
      counts_limit_a: 0
      limit_a_is_fwd: true
      calibration_vel: 0.25
    - name: "joint_a"
      driver_voltage: 36.0
      motor_max_voltage: 24.0
      voltage_multiplier: 0.75
      mcu_id: 1
      motor_id: 0
      quad_cpr: -28800.0
      kP: -0.005
      kI: -0.0
      inversion: -1.0
      limit_a_present: false
      limit_b_present: false
    - name: "joint_b"
      driver_voltage: 36.0
      motor_max_voltage: 12.0
      mcu_id: 2
      motor_id: 0
      quad_cpr: 4096.0
      kP: -0.1
      kI: -0.0
      inversion: -1.0
      limit_a_present: true
      limit_b_present: false
      counts_limit_a: 0
      limit_a_is_fwd: true
      calibration_vel: 0.25
    - name: "joint_f"
      driver_voltage: 12.0
      motor_max_voltage: 8.0
      mcu_id: 1
      motor_id: 1
      quad_cpr: -2048.0
      kP: 0.05
      kI: 0.0
      inversion: -1.0
      limit_a_present: false
      limit_b_present: false
    - name: "finger"
      driver_voltage: 12.0
      motor_max_voltage: 12.0
      mcu_id: 1
      motor_id: 3
      inversion: 1.0
      limit_a_present: true
      limit_b_present: true
      counts_limit_a: 0
      counts_limit_b: 0
      limit_a_is_fwd: true
      calibration_vel: 0.25
    - name: "gripper"
      driver_voltage: 12.0
      motor_max_voltage: 12.0
      mcu_id: 1
      motor_id: 2
      inversion: 1.0
      limit_a_present: false
      limit_b_present: false
    - name: "mast_gimbal_up_down"
      driver_voltage: 12.0
      motor_max_voltage: 12.0
      mcu_id: 2
      motor_id: 4
      inversion: -1.0
      limit_a_present: false
      limit_b_present: false
    - name: "mast_gimbal_left_right"
      driver_voltage: 12.0
      motor_max_voltage: 12.0
      mcu_id: 2
      motor_id: 3
      inversion: -1.0
      limit_a_present: false
      limit_b_present: false
    - name: "microscope"
      driver_voltage: 12.0
      motor_max_voltage: 12.0
      mcu_id: 1
      motor_id: 4
      inversion: 1.0
      limit_a_present: true
      limit_b_present: true
      counts_limit_a: 0
      counts_limit_b: 0
      limit_a_is_fwd: false
      calibration_vel: 0.25
    - name: "sa_joint_1"
      driver_voltage: 36.0
      motor_max_voltage: 12.0
      mcu_id: 1
      motor_id: 0
      inversion: 1.0
      limit_a_present: true
      limit_b_present: false
      counts_limit_a: 0
      limit_a_is_fwd: true
      calibration_vel: 0.25
    - name: "sa_joint_2"
      driver_voltage: 12.0
      motor_max_voltage: 12.0
      mcu_id: 1
      motor_id: 1
      inversion: -1.0
      limit_a_present: true
      limit_b_present: false
      counts_limit_a: 0
      limit_a_is_fwd: false
      calibration_vel: 0.25
    - name: "sa_joint_3"
      driver_voltage: 12.0
      motor_max_voltage: 12.0
      mcu_id: 1
      motor_id: 2
      inversion: -1.0
      limit_a_present: true
      limit_b_present: false
      counts_limit_a: 0
      limit_a_is_fwd: true
      calibration_vel: 0.25
    - name: "scoop"
      driver_voltage: 12.0
      motor_max_voltage: 12.0
      mcu_id: 1
      motor_id: 3
      inversion: 1.0
      limit_a_present: true
      limit_b_present: true
      counts_limit_a: 0
      counts_limit_b: 0
      limit_a_is_fwd: false
      calibration_vel: 0.25
  i2c_device_file: "/dev/i2c-1"
  test: false
  
cameras:
  arguments:
    - bps: 173000
      width: 320
      height: 240
      fps: 15
    - bps: 691000
      width: 640
      height: 480
      fps: 15
    - bps: 2000000
      width: 960
      height: 720
      fps: 15
    - bps: 3000000
      width: 1280
      height: 720
      fps: 15
    - bps: 4200000
      width: 1280
      height: 720
      fps: 30

  # Number of devices corresponds to number of cmds in
  #   - ChangeCameras.srv
  #   - ResetCameras.srv
  max_streams: 4
  max_device_id: 10
  ips:
    primary: "10.0.0.7"
    secondary: "10.0.0.8"
  # Jetsons for some reason give two IDs (ie. 0 and 1) for each USB camera.
  devices_doubled: true

science:
  auton_color_ids:
    red: 0
    green: 1
    blue: 2
    "off": 3
  device_mosfet_numbers:
    arm_laser: 6
    uv_led_carousel: 1
    uv_led_end_effector: 6
    white_led: 2
  serial:
    baud_rate: 9600
    timeout: 0
    port: "/dev/ttyTHS0" 
  # These position are random for now
  syringe_servo_positions:  # This is in degrees
    site_A:
      pushed: 80
      start: 100
    site_B:
      pushed: 60
      start: 90
    site_C:
      pushed: 10
      start: 50
  info:
    num_diag_current: 3
    num_diag_thermistors: 3
    num_science_thermistors: 3
    num_spectral: 1
    sleep: 0.01
    uart_transmit_msg_len: 30

rover:
  length: 0.86
  width: 0.86
  max_speed: 2.0

wheel:
  gear_ratio: 50.0
  radius: 0.13

brushless:
  using_pi3_hat: true
  drive:
    max_torque: 0.3
    controllers:
      FrontLeft:
        id: 2
        bus: 1
        multiplier: -1
      FrontRight:
        id: 3
        bus: 2
        multiplier: 1
      MiddleLeft:
        id: 1
        bus: 1
        multiplier: -1
      MiddleRight:
        id: 4
        bus: 2
        multiplier: 1
      BackLeft:
        id: 0
        bus: 1
        multiplier: -1
      BackRight:
        id: 5
        bus: 2
        multiplier: -1
  arm:
    controllers:
      joint_c:
        id: 6
        bus: 3
        max_rps: 80
        max_torque: 0.7
        multiplier: -1
      joint_d:
        id: 7
        bus: 3
        max_rps: 80
        max_torque: 0.13
        multiplier: 1
      joint_e:
        id: 8
        bus: 3
        max_rps: 70
        max_torque: 0.13
        multiplier: -1

default_network_iface: "enp0s31f6"
