gps_driver:
  port: "/dev/gps"
  baud: 115200
  useRMC: false # get covariance instead of velocity, see wiki for more info
  frame_id: "base_link"

imu_driver:
  port: "/dev/imu"
  baud: 115200
  frame_id: "imu_link"

odrive:
  axis:
    left: 0
    right: 1
  config:
    current_lim: 4
    watchdog_timeout: 0.1
  ids:
    front: "335D36623539"
    middle: "205535833056"
    back: "2066377F5753"
  ratio:
    meters_to_turns_ratio_left: -39.793
    meters_to_turns_ratio_right: 39.793
    turns_to_raw_ratio_left: -50.0
    turns_to_raw_ratio_right: 50.0
  ros:
    publish_rate_hz: 20

cameras:
    input:
        - resolution: 144
          arguments:
            - "--headless"
            - "--bitrate=300000"
            - "--width=256"
            - "--height=144"
        - resolution: 360
          arguments: 
            - "--headless"
            - "--bitrate=800000"
            - "--width=480"
            - "--height=360"
        - resolution: 720
          arguments:
            - "--headless"
            - "--bitrate=1800000"
            - "--width=1280"
            - "--height=720"
    default_mission: "erd"
    max_video_device_id_number: 10
    missions:
        - name: auton
          streams:
          - endpoint: "10.0.0.1:5000"
            resolution: 144
          - endpoint: "10.0.0.1:5001"
            resolution: 144
        - name: erd
          streams:
          - endpoint: "10.0.0.1:5000"
            resolution: 144
          - endpoint: "10.0.0.1:5001"
            resolution: 144
        - name: es
          streams:
          - endpoint: "10.0.0.1:5000"
            resolution: 720
          - endpoint: "10.0.0.1:5001"
            resolution: 720
        - name: science
          streams:
          - endpoint: "10.0.0.1:5000"
            resolution: 144
          - endpoint: "10.0.0.1:5001"
            resolution: 144
          - endpoint: "10.0.0.2:5000"
            resolution: 144
          - endpoint: "10.0.0.2:5001"
            resolution: 144
    number_of_pipelines: 4