gps_driver:
  port: "/dev/gps"
  baud: 115200
  useRMC: false # get covariance instead of velocity, see wiki for more info
  frame_id: "base_link"

imu_driver:
  port: "/dev/imu"
  baud: 115200
  frame_id: "imu_link"

odrive:
  axis:
    left: 0
    right: 1
  config:
    current_lim: 4
    watchdog_timeout: 0.1
  ids:
    front: "335D36623539"
    middle: "205535833056"
    back: "2066377F5753"
  ratio:
    direction_left: -1.0
    direction_right: 1.0
  ros:
    publish_rate_hz: 20
  publish_index:
    front_left: 0
    front_right: 1
    middle_left: 2
    middle_right: 3
    back_left: 4
    back_right: 5

science:
  color_ids:
    red: 0
    blue: 1
    green: 2
    "off": 3
  device_mosfet_numbers:
    arm_laser: 1
    heater_0: 7
    heater_1: 8
    heater_2: 9
    uv_led_carousel: 4
    uv_led_end_effector: 1
    white_led: 5
  serial:
    baud_rate: 38400
    timeout: 0
    port: "/dev/ttyTHS0"
  # These position are random for now
  # Please configure once we know what positions we want to turn them to
  syringe_servo_positions:
    site_A: 135
    site_B: 120
    site_C: 140
  info:
    sleep: 0.01
    science_thermistors: 3
    diag_thermistors: 3
    diag_current: 3
    spectral: 1
    sa_data: 4
    uart_transmit_msg_len: 30

rover:
  length: 0.86
  width: 0.86
  max_speed: 0.8

wheel:
  gear_ratio: 50.0
  radius: 0.13

brushless:
  using_pi3_hat: false
  drive:
    FrontLeft:
      id: 0
    FrontRight:
      id: 1
    MiddleLeft:
      id: 2
    MiddleRight:
      id: 3
    BackLeft:
      id: 4
    BackRight:
      id: 5
