gps_driver:
  port: "/dev/gps"
  baud: 115200
  useRMC: false # get covariance instead of velocity, see wiki for more info

imu_driver:
  port: "/dev/imu"
  baud: 115200
  frame_id: "imu_link"

brushed_motors:
  controllers:
    - name: "ra_joint_a"
      driver_voltage: 36.0
      motor_max_voltage: 24.0
      voltage_multiplier: 0.44
      nucleo: 0
      channel: 0
      quad_cpr: -28800.0
      kP: -0.005
      kI: -0.0
      inversion: -1.0
    - name: "ra_joint_b"
      driver_voltage: 36.0
      motor_max_voltage: 12.0
      nucleo: 0
      channel: 1
      quad_cpr: 4096.0
      kP: -0.1
      kI: -0.0
      inversion: 1.0
    - name: "ra_joint_c"
      driver_voltage: 36.0
      motor_max_voltage: 24.0
      nucleo: 0
      channel: 1
      quad_cpr: 136800.0
      kP: -0.005
      kI: -0.0
      inversion: 1.0
    - name: "ra_joint_d"
      driver_voltage: 36.0
      motor_max_voltage: 24.0
      nucleo: 1
      channel: 1
      quad_cpr: 72000.0
      kP: -0.005
      kI: -0.0
      inversion: 1.0
    - name: "ra_joint_e"
      driver_voltage: 36.0
      motor_max_voltage: 24.0
      nucleo: 2
      channel: 0
      quad_cpr: -72000.0
      kP: -0.005
      kI: -0.0
      inversion: 1.0
    - name: "ra_joint_f"
      driver_voltage: 36.0
      motor_max_voltage: 24.0
      nucleo: 2
      channel: 1
      quad_cpr: -2048.0
      kP: 0.05
      kI: 0.0
      inversion: 1.0
    - name: "ra_finger"
      driver_voltage: 12.0
      motor_max_voltage: 12.0
      nucleo: 2
      channel: 2
      inversion: 1.0
    - name: "ra_gripper"
      driver_voltage: 12.0
      motor_max_voltage: 12.0
      nucleo: 1
      channel: 2
      inversion: 1.0
  i2c_device_file: "/dev/i2c-1"

odrive:
  axis:
    left: 0
    right: 1
  config:
    current_lim: 4
    watchdog_timeout: 0.1
  ids:
    front: "335D36623539"
    middle: "205535833056"
    back: "2066377F5753"
  ratio:
    meters_to_turns_ratio_left: -39.793
    meters_to_turns_ratio_right: 39.793
    turns_to_raw_ratio_left: -50.0
    turns_to_raw_ratio_right: 50.0
  ros:
    publish_rate_hz: 20
