rover_gps_driver:
  port: "/dev/gps"
  baud: 38400
  frame_id: "base_link"

basestation_gps_driver:
  port: "/dev/gps"
  baud: 38400
  frame_id: "base_link"

imu_driver:
  frame_id: "base_link"

can:
  devices:
    - name: "jetson"
      bus: 0
      id: 0x10
    - name: "jetson"
      bus: 1
      id: 0x10
    - name: "jetson"
      bus: 2
      id: 0x10
    - name: "jetson"
      bus: 3
      id: 0x10
    - name: "front_left"
      bus: 2
      id: 0x12
    - name: "front_right"
      bus: 2
      id: 0x11
    - name: "middle_left"
      bus: 2
      id: 0x14
    - name: "middle_right"
      bus: 2
      id: 0x13
    - name: "back_left"
      bus: 2
      id: 0x16
    - name: "back_right"
      bus: 2
      id: 0x15
    - name: "joint_a"
      bus: 1
      id: 0x20  
    - name: "joint_b"
      bus: 1
      id: 0x21
    - name: "joint_c"
      bus: 1
      id: 0x22
    - name: "joint_de_0"
      bus: 1
      id: 0x23
    - name: "joint_de_1"
      bus: 1
      id: 0x24
    - name: "allen_key"
      bus: 1
      id: 0x25
    - name: "gripper"
      bus: 1
      id: 0x26
    - name: "mast_gimbal_y"
      bus: 3
      id: 0x30
    - name: "mast_gimbal_z"
      bus: 3
      id: 0x28
    - name: "sa_x"
      bus: 1
      id: 0x29
    - name: "sa_y"
      bus: 1
      id: 0x27
    - name: "sa_z"
      bus: 1
      id: 0x31
    - name: "sampler"
      bus: 1
      id: 0x32
    - name: "sensor_actuator"
      bus: 1
      id: 0x33
    - name: "cache_motor"
      bus: 1
      id: 0x34
    - name: "pdlb"
      bus: 3
      id: 0x50
    - name: "science"
      bus: 1
      id: 0x51

brushless_motors:
  controllers:
    front_left:
      min_velocity: -2.0
      max_velocity: 2.0
      max_torque: 25.0
    front_right:
      min_velocity: -2.0
      max_velocity: 2.0
      max_torque: 25.0
    middle_left:
      min_velocity: -2.0
      max_velocity: 2.0
      max_torque: 25.0
    middle_right:
      min_velocity: -2.0
      max_velocity: 2.0
      max_torque: 25.0
    back_left:
      min_velocity: -2.0
      max_velocity: 2.0
      max_torque: 25.0
    back_right:
      min_velocity: -2.0
      max_velocity: 2.0
      max_torque: 25.0
    joint_a:
      # 1236.8475 rad/meter, or 196.850393476 rev/meter, and we want a max vel of 40 meter/s.
      # gear ratio is currently at 0.005080 revolutions = 1 meter
      min_velocity: -0.05  # this means -0.10 meters per second.
      max_velocity: 0.05
      limit_0_present: true
      limit_1_present: true
      limit_0_enabled: true
      limit_1_enabled: true
      limit_0_limits_fwd: true
      limit_1_limits_fwd: false
      limit_0_is_active_high: false
      limit_1_is_active_high: false
      limit_0_used_for_readjustment: true
      limit_1_used_for_readjustment: true
      limit_0_readjust_position: 0.4
      limit_1_readjust_position: 0.0
      limit_max_forward_pos: true
      limit_max_backward_pos: true
      max_forward_pos: 0.4
      max_backward_pos: 0.0
      max_torque: 20.0
    joint_c:
      min_velocity: -0.03 # in terms of output
      max_velocity: 0.03 # max output shaft speed: 5 rpm (for now)
      min_position: -0.125
      max_position: 0.30 # 220 degrees of motion is the entire range
      max_torque: 200.0
    joint_de_0:
      min_velocity: -5.0
      max_velocity: 5.0
      min_position: -10000.0
      max_position: 10000.0
      max_torque: 20.0
    joint_de_1:
      min_velocity: -5.0
      max_velocity: 5.0
      min_position: -10000.0
      max_position: 10000.0
      max_torque: 20.0
    sa_z:
      min_velocity: -0.03
      max_velocity: 0.03
      min_position: 0.0
      max_position: 0.6007
      limit_0_present: true
      limit_1_present: true
      limit_0_enabled: true
      limit_1_enabled: true
      limit_0_limits_fwd: false
      limit_1_limits_fwd: true
      limit_0_is_active_high: false
      limit_1_is_active_high: false
      limit_0_used_for_readjustment: true
      limit_1_used_for_readjustment: true
      limit_0_readjust_position: 0.0 # meters 
      limit_1_readjust_position: 0.6007 # meters 
      max_torque: 500.0

brushed_motors:
  controllers:
    # example_name:
    #   gear_ratio: 1.0  # motor ratio compared to joint, e.g. if 5, then 5 rotations of motor = 1 rotation of joint
    #   limit_0_present: false
    #   limit_1_present: false
    #   limit_2_present: false
    #   limit_3_present: false
    #   limit_0_enabled: false
    #   limit_1_enabled: false
    #   limit_2_enabled: false
    #   limit_3_enabled: false
    #   limit_0_is_active_high: true
    #   limit_1_is_active_high: true
    #   limit_2_is_active_high: true
    #   limit_3_is_active_high: true
    #   limit_0_limits_fwd: true
    #   limit_1_limits_fwd: true
    #   limit_2_limits_fwd: true
    #   limit_3_limits_fwd: true
    #   limit_0_used_for_readjustment: false
    #   limit_1_used_for_readjustment: false
    #   limit_2_used_for_readjustment: false
    #   limit_3_used_for_readjustment: false
    #   quad_present: false
    #   quad_is_fwd_polarity: true
    #   abs_present: false
    #   abs_is_fwd_polarity: true
    #   limit_0_readjust_position: 0.0  # radians
    #   limit_1_readjust_position: 0.0  # radians
    #   limit_2_readjust_position: 0.0  # radians
    #   limit_3_readjust_position: 0.0  # radians
    #   quad_ratio: 1.0  # encoder ratio compared to motor
    #   abs_ratio: 1.0  # encoder ratio compared to motor
    #   abs_offset: 0.0 # 0 for joint position corresponds to this radians reading by absolute encoder
    #   driver_voltage: 10.5  # used to calculate max pwm
    #   motor_max_voltage: 12.0  # used to calculate max pwm
    #   limit_max_forward_pos: false
    #   limit_max_backward_pos: false
    #   max_forward_pos: 1.0
    #   max_backward_pos: 0.0
    #   calibration_throttle: 5.0
    joint_b:
      is_inverted: False
      gear_ratio: 1.0 # motor ratio compared to joint, e.g. if 5, then 5 rotations of motor = 1 rotation of joint
      limit_0_present: true
      limit_0_enabled: true
      limit_0_is_active_high: false
      limit_0_limits_fwd: false
      limit_0_used_for_readjustment: false
      abs_present: true
      abs_is_fwd_polarity: true
      abs_ratio: 1.0 # encoder ratio compared to motor
      abs_offset: 0.0 # 0 for joint position corresponds to this radians reading by absolute encoder
      driver_voltage: 10.5 # used to calculate max pwm
      motor_max_voltage: 12.0 # used to calculate max pwm
      limit_max_forward_pos: true
      min_position: -0.7853981633974483
      max_position: 0.0
      min_velocity: -1.0
      max_velocity: 1.0
      calibration_throttle: 0.5  # throttle during calibration
    allen_key:
      gear_ratio: 30.0 # motor ratio compared to joint, e.g. if 5, then 5 rotations of motor = 1 rotation of joint
      limit_0_present: true
      limit_1_present: true
      limit_0_enabled: true
      limit_1_enabled: true
      limit_0_is_active_high: false
      limit_1_is_active_high: false
      limit_0_limits_fwd: true
      limit_1_limits_fwd: true
      limit_0_used_for_readjustment: true
      limit_1_used_for_readjustment: true
      quad_present: true
      quad_is_fwd_polarity: true
      limit_0_readjust_position: 0.0 # radians
      limit_1_readjust_position: 0.0 # radians
      quad_ratio: 1.0 # encoder ratio compared to motor
      driver_voltage: 10.5 # used to calculate max pwm
      motor_max_voltage: 12.0 # used to calculate max pwm
      calibration_throttle: 0.9  # throttle during calibration, does not move unless close to max voltage
    gripper:
      gear_ratio: 47.0 # motor ratio compared to joint, e.g. if 5, then 5 rotations of motor = 1 rotation of joint
      quad_present: false
      quad_is_fwd_polarity: true
      abs_present: false
      abs_is_fwd_polarity: true
      quad_ratio: 1.0 # encoder ratio compared to motor
      driver_voltage: 10.5 # used to calculate max pwm
      motor_max_voltage: 12.0 # used to calculate max pwm
      calibration_throttle: 0.5  # throttle during calibration
    mast_gimbal_y:
      gear_ratio: 1000.0 # motor ratio compared to joint, e.g. if 5, then 5 rotations of motor = 1 rotation of joint
      quad_present: true
      quad_is_fwd_polarity: true
      quad_ratio: 1.0
      driver_voltage: 10.5 # used to calculate max pwm
      motor_max_voltage: 12.0 # used to calculate max pwm
    mast_gimbal_z:
      gear_ratio: 1000.0 # motor ratio compared to joint, e.g. if 5, then 5 rotations of motor = 1 rotation of joint
      quad_present: true
      quad_is_fwd_polarity: true
      quad_ratio: 1.0
      driver_voltage: 10.5 # used to calculate max pwm
      motor_max_voltage: 12.0 # used to calculate max pwm
    sa_x:
      is_inverted: true
      gear_ratio: 75.0 # motor ratio compared to joint, e.g. if 5, then 5 rotations of motor = 1 rotation of joint
      rad_to_meters_ratio: 1.0 #TODO 5.0 = 5 motor radians -> 1 meter
      limit_0_present: true
      limit_1_present: true
      limit_2_present: false
      limit_0_enabled: true
      limit_1_enabled: true
      limit_2_enabled: true
      limit_0_is_active_high: false
      limit_1_is_active_high: false
      limit_2_is_active_high: false
      limit_0_limits_fwd: false
      limit_1_limits_fwd: true
      limit_2_limits_fwd: false
      limit_0_used_for_readjustment: true
      limit_1_used_for_readjustment: true
      limit_2_used_for_readjustment: false
      quad_present: true
      quad_is_fwd_polarity: true
      limit_0_readjust_position: 0.0 # meters
      limit_1_readjust_position: 0.2452 # meters
      quad_ratio: 48.0 # encoder ratio compared to motor
      driver_voltage: 10.0 # used to calculate max pwm
      motor_max_voltage: 12.0 # used to calculate max pwm
      min_velocity: -1.0
      max_velocity: 1.0
      min_position: 0.0
      max_position: 0.2452
      calibration_throttle: 0.5  # throttle during calibration
    sa_y:
      gear_ratio: 75.0 # motor ratio compared to joint, e.g. if 5, then 5 rotations of motor = 1 rotation of joint
      rad_to_meters_ratio: 1.0 #TODO 5.0 = 5 motor radians -> 1 meter
      limit_0_present: true
      limit_1_present: true
      limit_0_enabled: true
      limit_1_enabled: true
      limit_0_is_active_high: false
      limit_1_is_active_high: false
      limit_0_limits_fwd: true
      limit_1_limits_fwd: false
      limit_0_used_for_readjustment: true
      limit_1_used_for_readjustment: true
      quad_present: true
      quad_is_fwd_polarity: true
      limit_0_readjust_position: 0.4356 # meters
      limit_1_readjust_position: 0.0 # meters
      quad_ratio: 48.0 # encoder ratio compared to motor
      driver_voltage: 10.5 # used to calculate max pwm
      motor_max_voltage: 6.0 # used to calculate max pwm
      min_velocity: -1.0
      max_velocity: 1.0
      min_position: 0.0
      max_position: 0.4356
      calibration_throttle: 0.5  # throttle during calibration
    sampler:
      gear_ratio: 75.0 # motor ratio compared to joint, e.g. if 5, then 5 rotations of motor = 1 rotation of joint
      rad_to_meters_ratio: 1.0 #TODO 5.0 = 5 motor radians -> 1 meter
      limit_0_present: false
      limit_1_present: false
      limit_0_enabled: false
      limit_1_enabled: false
      limit_0_is_active_high: false
      limit_1_is_active_high: false
      limit_0_limits_fwd: true
      limit_1_limits_fwd: false
      limit_0_used_for_readjustment: true
      limit_1_used_for_readjustment: true
      quad_present: true
      quad_is_fwd_polarity: true
      limit_0_readjust_position: 0.0 # radians
      limit_1_readjust_position: 0.0 # radians
      quad_ratio: 48.0 # encoder ratio compared to motor
      driver_voltage: 8.0 # used to calculate max pwm
      motor_max_voltage: 12.0 # used to calculate max pwm
      calibration_throttle: 0.5  # throttle during calibration
    sensor_actuator:
      gear_ratio: 1.0 # motor ratio compared to joint, e.g. if 5, then 5 rotations of motor = 1 rotation of joint
      limit_0_present: false
      limit_1_present: false
      limit_0_enabled: false
      limit_1_enabled: false
      limit_0_is_active_high: false
      limit_1_is_active_high: false
      limit_0_limits_fwd: true
      limit_1_limits_fwd: false
      limit_0_used_for_readjustment: true
      limit_1_used_for_readjustment: true
      limit_0_readjust_position: 0.0 # radians
      limit_1_readjust_position: 0.0 # radians
      driver_voltage: 12.0 # used to calculate max pwm
      motor_max_voltage: 12.0 # used to calculate max pwm
    cache_motor:
      gear_ratio: 1.0 # motor ratio compared to joint, e.g. if 5, then 5 rotations of motor = 1 rotation of joint
      limit_0_present: false
      limit_1_present: false
      limit_0_enabled: true
      limit_1_enabled: true
      limit_0_is_active_high: false
      limit_1_is_active_high: false
      limit_0_limits_fwd: true
      limit_1_limits_fwd: false
      limit_0_used_for_readjustment: true
      limit_1_used_for_readjustment: true
      limit_0_readjust_position: 0.0 # radians
      limit_1_readjust_position: 0.0 # radians
      driver_voltage: 10.5 # used to calculate max pwm
      motor_max_voltage: 12.0 # used to calculate max pwm

rover:
  length: 0.86
  width: 0.86
  max_speed: 1.0

wheel:
  radius: 0.13

motors_group:
  arm_direct:
    - "joint_a"
    - "joint_b"
    - "joint_c"
    - "joint_de_0"
    - "joint_de_1"
    - "allen_key"
    - "gripper"
  mast_gimbal:
    - "mast_gimbal_y"
    - "mast_gimbal_z"
  cache:
    - "cache_motor"
  sa:
    - "sa_x"
    - "sa_y"
    - "sa_z"
    - "sampler"
    - "sensor_actuator"
  drive_left:
    - "front_left"
    - "middle_left"
    - "back_left"
  drive_right:
    - "front_right"
    - "middle_right"
    - "back_right"

motors:
  controllers:
    joint_a:
      type: "brushless_linear"
    joint_b:
      type: "brushed"
    joint_c:
      type: "brushless"
    joint_de_0:
      type: "brushless"
    joint_de_1:
      type: "brushless"
    allen_key:
      type: "brushed"
    gripper:
      type: "brushed"
    front_left:
      type: "brushless"
    front_right:
      type: "brushless"
    middle_left:
      type: "brushless"
    middle_right:
      type: "brushless"
    back_left:
      type: "brushless"
    back_right:
      type: "brushless"
    mast_gimbal_y:
      type: "brushed"
    mast_gimbal_z:
      type: "brushed"
    sa_x:
      type: "brushed"
    sa_y:
      type: "brushed"
    sa_z:
      type: "brushless"
    sampler:
      type: "brushed"
    sensor_actuator:
      type: "brushed"
    cache_motor:
      type: "brushed"

auton_led_driver:
  port: "/dev/led"
  baud: 115200

science:
  shutoff_temp: 50.0f
