auton_led_driver:
  port: "/dev/ttyACM0"
  baud: 115200

gps_driver:
  port: "/dev/gps"
  baud: 115200
  useRMC: false # get covariance instead of velocity, see wiki for more info
  frame_id: "base_link"

imu_driver:
  port: "/dev/imu"
  baud: 115200
  frame_id: "imu_link"

brushed_motors:
  controllers:
    - name: "cache"
      driver_voltage: 12.0
      motor_max_voltage: 12.0
      mcu_id: 2
      motor_id: 2
      inversion: 1.0
    - name: "carousel"
      driver_voltage: 12.0
      motor_max_voltage: 12.0
      mcu_id: 2
      motor_id: 1
      inversion: 1.0
    - name: "joint_a"
      driver_voltage: 36.0
      motor_max_voltage: 24.0
      voltage_multiplier: 0.75
      mcu_id: 1
      motor_id: 0
      quad_cpr: -28800.0
      kP: -0.005
      kI: -0.0
      inversion: -1.0
    - name: "joint_b"
      driver_voltage: 36.0
      motor_max_voltage: 12.0
      mcu_id: 2
      motor_id: 0
      quad_cpr: 4096.0
      kP: -0.1
      kI: -0.0
      inversion: -1.0
    - name: "joint_f"
      driver_voltage: 12.0
      motor_max_voltage: 8.0
      mcu_id: 1
      motor_id: 1
      quad_cpr: -2048.0
      kP: 0.05
      kI: 0.0
      inversion: -1.0
    - name: "finger"
      driver_voltage: 12.0
      motor_max_voltage: 12.0
      mcu_id: 1
      motor_id: 3
      inversion: 1.0
    - name: "gripper"
      driver_voltage: 12.0
      motor_max_voltage: 12.0
      mcu_id: 1
      motor_id: 2
      inversion: 1.0
    - name: "mast_gimbal_up_down"
      driver_voltage: 12.0
      motor_max_voltage: 12.0
      mcu_id: 2
      motor_id: 4
      inversion: -1.0
    - name: "mast_gimbal_left_right"
      driver_voltage: 12.0
      motor_max_voltage: 12.0
      mcu_id: 2
      motor_id: 3
      inversion: -1.0
    - name: "microscope"
      driver_voltage: 12.0
      motor_max_voltage: 12.0
      mcu_id: 1
      motor_id: 4
      inversion: 1.0
    - name: "sa_joint_1"
      driver_voltage: 36.0
      motor_max_voltage: 12.0
      mcu_id: 1
      motor_id: 0
      inversion: 1.0
    - name: "sa_joint_2"
      driver_voltage: 12.0
      motor_max_voltage: 12.0
      mcu_id: 1
      motor_id: 1
      inversion: 1.0
    - name: "sa_joint_3"
      driver_voltage: 12.0
      motor_max_voltage: 12.0
      mcu_id: 1
      motor_id: 2
      inversion: 1.0
    - name: "scoop"
      driver_voltage: 12.0
      motor_max_voltage: 12.0
      mcu_id: 1
      motor_id: 3
      inversion: 1.0
  i2c_device_file: "/dev/i2c-1"
  test: false

cameras:
    arguments:
      144_res:
        - "--headless"
        - "--bitrate=300000"
        - "--width=256"
        - "--height=144"
      360_res:
        - "--headless"
        - "--bitrate=800000"
        - "--width=480"
        - "--height=360"
      720_res:
        - "--headless"
        - "--bitrate=1800000"
        - "--width=1280"
        - "--height=720"
    max_video_device_id_number: 10
    endpoints:
      primary_0: "10.0.0.7:5000"
      primary_1: "10.0.0.7:5001"
      primary_2: "10.0.0.7:5002"
      primary_3: "10.0.0.7:5003"
      secondary_0: "10.0.0.8:5000"
      secondary_1: "10.0.0.8:5001"
      secondary_2: "10.0.0.8:5002"
      secondary_3: "10.0.0.8:5003"
    skip_every_other_device: true

rover:
  length: 0.86
  width: 0.86
  max_speed: 2.0

wheel:
  gear_ratio: 50.0
  radius: 0.13

brushless:
  using_pi3_hat: true
  drive:
    max_torque: 0.3
    controllers:
      FrontLeft:
        id: 3
        multiplier: -1
      FrontRight:
        id: 0
        multiplier: 1
      MiddleLeft:
        id: 4
        multiplier: -1
      MiddleRight:
        id: 1
        multiplier: 1
      BackLeft:
        id: 5
        multiplier: -1
      BackRight:
        id: 2
        multiplier: 1
  arm:
    controllers:
      joint_c:
        id: 6
        max_rps: 50
        max_torque: 0.3
        multiplier: -1
      joint_d:
        id: 7
        max_rps: 80
        max_torque: 0.13
        multiplier: 1
      joint_e:
        id: 8
        max_rps: 70
        max_torque: 0.13
        multiplier: -1
