gps_driver:
  port: "/dev/gps"
  baud: 115200
  useRMC: false # get covariance instead of velocity, see wiki for more info

imu_driver:
  port: "/dev/imu"
  baud: 115200
  frame_id: "imu_link"

odrive:
  axis:
    left: 0
    right: 1
  config:
    current_lim: 4
    watchdog_timeout: 0.1
  ids:
    front: "335D36623539"
    middle: "205535833056"
    back: "2066377F5753"
  ratio:
    direction_left: -1.0
    direction_right: 1.0
  ros:
    publish_rate_hz: 20

wheels:
  base: 0.86
  radius: 0.13
  ratio: 50.0
  max_speed: 1.0