gps_driver:
  port: "/dev/gps"
  baud: 115200
  useRMC: false # get covariance instead of velocity, see wiki for more info

imu_driver:
  port: "/dev/imu"
  baud: 115200
  frame_id: "imu_link"

odrive:
  axis:
    left: 0
    right: 1
  config:
    current_lim: 4
    watchdog_timeout: 0.1
  ids:
    front: "335D36623539"
    middle: "205535833056"
    back: "2066377F5753"
  ratio:
    meters_to_turns_ratio_left: -39.793
    meters_to_turns_ratio_right: 39.793
    turns_to_raw_ratio_left: -50.0
    turns_to_raw_ratio_right: 50.0
  ros:
    publish_rate_hz: 20

science_board:
  color_ids:
    red: 0
    blue: 1
    green: 2
    "off": 3
  device_mosfet_numbers:
    arm_laser: 1
    heater_0: 7
    heater_1: 8
    heater_2: 9
    uv_led_carousel: 4
    uv_led_end_effector: 1
    white_led: 5
  serial:
    baud_rate: 38400
    timeout: 0
    port: "/dev/ttyTHS0"
  info:
    sleep: 0.01
    science_thermistors: 3
    diag_thermistors: 3
    diag_current: 3
    spectral: 1

    uart_transmit_msg_len: 30