auton_led_driver:
  port: "/dev/ttyACM0"
  baud: 115200

gps_driver:
  port: "/dev/gps"
  baud: 115200
  useRMC: false # get covariance instead of velocity, see wiki for more info
  frame_id: "base_link"

imu_driver:
  port: "/dev/imu"
  baud: 115200
  frame_id: "imu_link"

brushed_motors:
  controllers:
    - name: "joint_a"
      driver_voltage: 36.0
      motor_max_voltage: 24.0
      voltage_multiplier: 0.44
      nucleo: 1
      channel: 0
      quad_cpr: -28800.0
      kP: -0.005
      kI: -0.0
      inversion: -1.0
    - name: "joint_b"
      driver_voltage: 36.0
      motor_max_voltage: 12.0
      nucleo: 1
      channel: 1
      quad_cpr: 4096.0
      kP: -0.1
      kI: -0.0
      inversion: 1.0
    - name: "joint_c"
      driver_voltage: 36.0
      motor_max_voltage: 24.0
      nucleo: 2
      channel: 0
      quad_cpr: 136800.0
      kP: -0.005
      kI: -0.0
      inversion: 1.0
    - name: "joint_d"
      driver_voltage: 36.0
      motor_max_voltage: 24.0
      nucleo: 2
      channel: 1
      quad_cpr: 72000.0
      kP: -0.005
      kI: -0.0
      inversion: 1.0
    - name: "joint_e"
      driver_voltage: 36.0
      motor_max_voltage: 24.0
      nucleo: 3
      channel: 0
      quad_cpr: -72000.0
      kP: -0.005
      kI: -0.0
      inversion: 1.0
    - name: "joint_f"
      driver_voltage: 36.0
      motor_max_voltage: 24.0
      nucleo: 3
      channel: 1
      quad_cpr: -2048.0
      kP: 0.05
      kI: 0.0
      inversion: 1.0
    - name: "finger"
      driver_voltage: 12.0
      motor_max_voltage: 12.0
      nucleo: 3
      channel: 2
      inversion: 1.0
    - name: "gripper"
      driver_voltage: 12.0
      motor_max_voltage: 12.0
      nucleo: 2
      channel: 2
      inversion: 1.0
    - name: "mast_up_down"
      driver_voltage: 12.0
      motor_max_voltage: 12.0
      nucleo: 3
      channel: 3
      inversion: -1.0
    - name: "mast_left_right"
      driver_voltage: 12.0
      motor_max_voltage: 12.0
      nucleo: 2
      channel: 3
      inversion: -1.0
  i2c_device_file: "/dev/i2c-1"
  test: false

science:
  color_ids:
    red: 0
    blue: 1
    green: 2
    "off": 3
  device_mosfet_numbers:
    arm_laser: 6
    uv_led_carousel: 1
    uv_led_end_effector: 6
    white_led: 2
  serial:
    baud_rate: 9600
    timeout: 0
    port: "/dev/ttyTHS1"
  # These position are random for now
  # TODO - Please configure once we know what positions we want to turn them to
  syringe_servo_positions:
    site_A:
      pushed: 135
      start: 104
    site_B:
      pushed: 135
      start: 103
    site_C:
      pushed: 135
      start: 102
  info:
    num_diag_current: 3
    num_diag_thermistors: 3
    num_science_thermistors: 3
    num_spectral: 1
    sleep: 0.01
    uart_transmit_msg_len: 30

rover:
  length: 0.86
  width: 0.86
  max_speed: 1.5

wheel:
  gear_ratio: 50.0
  radius: 0.13

brushless:
  using_pi3_hat: true
  drive:
    FrontLeft:
      id: 3
      multiplier: -1
    FrontRight:
      id: 0
      multiplier: 1
    MiddleLeft:
      id: 4
      multiplier: -1
    MiddleRight:
      id: 1
      multiplier: 1
    BackLeft:
      id: 5
      multiplier: -1
    BackRight:
      id: 2
      multiplier: 1
