gps_driver:
  port: "/dev/gps"
  baud: 115200
  useRMC: false # get covariance instead of velocity, see wiki for more info
  frame_id: "base_link"

imu_driver:
  port: "/dev/imu"
  baud: 115200
  frame_id: "imu_link"

odrive:
  axis:
    left: 0
    right: 1
  config:
    current_lim: 4
    watchdog_timeout: 0.1
  ids:
    front: "335D36623539"
    middle: "205535833056"
    back: "2066377F5753"
  ratio:
    meters_to_turns_ratio_left: -39.793
    meters_to_turns_ratio_right: 39.793
    turns_to_raw_ratio_left: -50.0
    turns_to_raw_ratio_right: 50.0
  ros:
    publish_rate_hz: 20

cameras:
    arguments:
      144_res:
        - "--headless"
        - "--bitrate=300000"
        - "--width=256"
        - "--height=144"
      360_res:
        - "--headless"
        - "--bitrate=800000"
        - "--width=480"
        - "--height=360"
      720_res:
        - "--headless"
        - "--bitrate=1800000"
        - "--width=1280"
        - "--height=720"
    max_video_device_id_number: 10
    endpoints:
      primary_0: "10.0.0.7:5000"
      primary_1: "10.0.0.7:5001"
      primary_2: "10.0.0.7:5002"
      primary_3: "10.0.0.7:5003"
      secondary_0: "10.0.0.8:5000"
      secondary_1: "10.0.0.8:5001"
      secondary_2: "10.0.0.8:5002"
      secondary_3: "10.0.0.8:5003"