process_noise_covariance: [0.1, 0, 0, 0, 0, 0, 0, 0, 0,
                           0, 0.1, 0, 0, 0, 0, 0, 0, 0,
                           0, 0, 0.1, 0, 0, 0, 0, 0, 0,
                           0, 0, 0, 0.1, 0, 0, 0, 0, 0,
                           0, 0, 0, 0, 0.1, 0, 0, 0, 0,
                           0, 0, 0, 0, 0, 0.1, 0, 0, 0,
                           0, 0, 0, 0, 0, 0, 0.1, 0, 0,
                           0, 0, 0, 0, 0, 0, 0, 0.1, 0,
                           0, 0, 0, 0, 0, 0, 0, 0, 0.1]

gps_covariance: [0.5, 0, 0,
                 0, 0.5, 0,
                 0, 0, 0.5]

accel_covariance: [0.5, 0, 0,
                   0, 0.5, 0,
                   0, 0, 0.5]

mag_covariance: [0.5, 0, 0,
                 0, 0.5, 0,
                 0, 0, 0.5]