gps_linearization:
  reference_point_latitude: 42.2
  reference_point_longitude: -83.7
  reference_point_altitude: 224

  use_odom_frame: false
  world_frame: "map"
  odom_frame: "odom"
  rover_frame: "base_link"