world_frame: "map"
odom_frame: "odom"
rover_frame: "base_link"
use_odom_frame: false

gps_linearization:
  reference_point_latitude: 42.2
  reference_point_longitude: -83.7
  reference_point_altitude: 224
  publish_tf: false