world_frame: "map"
odom_frame: "odom"
rover_frame: "base_link"
use_odom_frame: false

gps_linearization:
  reference_point_latitude: 38.4098
  reference_point_longitude: -110.78235
  reference_point_altitude: 1367.8429
  reference_heading: 90.0
