world_frame: "map"
odom_frame: "odom"
rover_frame: "base_link"
use_odom_frame: false

gps_linearization:
  reference_point_latitude: 42.293195
  reference_point_longitude: -83.7096706
  reference_point_altitude: 234.1
  reference_heading: 90.0
  use_both_gps: false

gps_covariance: [ [ 0.1, 0, 0 ],
                  [ 0, 0.1, 0 ],
                  [ 0, 0, 0.1 ] ]

imu_orientation_covariance: [ [ 0.1, 0, 0 ],
                              [ 0, 0.1, 0 ],
                              [ 0, 0, 0.1 ] ]