odrive:
  axis:
    # The side the ODrive axis controls
    # Should only be 0 or 1
    left: 0
    right: 1
  config:
    # Various ODrive config settings
    current_lim: 4
    watchdog_timeout: 0.1
  ids:
    # The ODrive IDs
    front: "335D36623539"
    middle: "335B36563539"
    back: "2066377F5753"
  info:
    # Scales normalized inputs to max physical speed of rover in turn/s
    # The magnitude should be same for both wheels, but sign may differ
    # This scales [0, 1] units to [0, 50] turns per second
    vel_cmd_multiplier_left: -50
    vel_cmd_multiplier_right: 50
    # Multipier to turn turns/sec to m/s (for 2022 rover)
    # The magnitude should be same for both wheels, but sign may differ
    vel_est_multiplier_left: 0.02513
    vel_est_multiplier_right: -0.02513
