zed:
  # HD2K    2208*1242 (x2) fps: 15
  # HD1080  1920*1080 (x2) fps: 15, 30
  # HD720   1280*720  (x2) fps: 15, 30, 60
  # VGA      672*376  (x2) fps: 15, 30, 60, 100
  grab_resolution: HD720
  grab_target_fps: 15
  # NONE        This mode does not compute any depth map. Only rectified stereo images will be available.
  # PERFORMANCE Computation mode optimized for speed.
  # QUALITY     Computation mode designed for challenging areas with untextured surfaces.
  # ULTRA       Computation mode favoring edges and sharpness. Requires more GPU memory and computation power.
  # NEURAL      End to End Neural disparity estimation, requires AI module.
  # NEURAL PLUS More accurate Neural disparity estimation, requires AI module.
  depth_mode: ULTRA
  image_width: 1280
  image_height: 720
  # Threshold to reject depth values based on their confidence.
  # Each depth pixel has a corresponding confidence. The confidence range is [1,100].
  # By default, the confidence threshold is set at 100, meaning that no depth pixel will be rejected.
  # Decreasing this value will remove depth data from both objects edges and low textured areas, to keep only confident depth estimation data.
  # Pixels with a value close to 100 are not to be trusted. Accurate depth pixels tends to be closer to lower values.
  # It can be seen as a probability of error, scaled to 100.
  depth_confidence: 70
  # Threshold to reject depth values based on their texture confidence. The texture confidence range is [1,100].
  # By default, the texture confidence threshold is set at 100, meaning that no depth pixel will be rejected.
  # Decreasing this value will remove depth data from image areas which are uniform.
  # Pixels with a value close to 100 are not to be trusted. Accurate depth pixels tends to be closer to lower values.
  texture_confidence: 100
  depth_maximum_distance: 12.0

zed_mini_auton:
  grab_resolution: VGA
  grab_target_fps: 15
  depth_mode: NONE
  image_width: 640
  image_height: 360

stereo_object_detector:
  model_score_threshold: 0.8
  # model_name: "urc_ver1"

long_range_object_detector:
  model_score_threshold: 0.8
  # model_name: "urc_ver1"

# cost_map:
#   z_threshold: 0
