zed_nodelet:
  # [0] HD2K    2208*1242 (x2) fps: 15
  # [1] HD1080  1920*1080 (x2) fps: 15, 30
  # [2] HD720   1280*720  (x2) fps: 15, 30, 60
  # [3] VGA      672*376  (x2) fps: 15, 30, 60, 100
  grab_resolution: 2
  grab_target_fps: 50
  # [0] NONE        This mode does not compute any depth map. Only rectified stereo images will be available.
  # [1] PERFORMANCE Computation mode optimized for speed.
  # [2] QUALITY     Computation mode designed for challenging areas with untextured surfaces.
  # [3] ULTRA       Computation mode favoring edges and sharpness. Requires more GPU memory and computation power.
  # [4] NEURAL      End to End Neural disparity estimation, requires AI module.
  depth_mode: 1
  image_width: 1280
  image_height: 720
  # Threshold to reject depth values based on their confidence.
  # Each depth pixel has a corresponding confidence. The confidence range is [1,100].
  # By default, the confidence threshold is set at 100, meaning that no depth pixel will be rejected.
  # Decreasing this value will remove depth data from both objects edges and low textured areas, to keep only confident depth estimation data.
  # Pixels with a value close to 100 are not to be trusted. Accurate depth pixels tends to be closer to lower values.
  # It can be seen as a probability of error, scaled to 100.
  depth_confidence: 85
  # Threshold to reject depth values based on their texture confidence. The texture confidence range is [1,100].
  # By default, the texture confidence threshold is set at 100, meaning that no depth pixel will be rejected.
  # Decreasing this value will remove depth data from image areas which are uniform.
  # Pixels with a value close to 100 are not to be trusted. Accurate depth pixels tends to be closer to lower values.
  texture_confidence: 100
  ues_builtin_visual_odom: true

tag_detector:
  doCornerRefinement: true
