# You will need to restart basestation.launch for
# Any changes to take effect
teleop:
  ra_names: ["joint_a", "joint_b", "joint_c", "joint_de_pitch", "joint_de_roll", "allen_key", "gripper"]
  ra_controls:
    joint_a:
      multiplier: -1
      slow_mode_multiplier: 0.5
      invert: True
      xbox_index: 0
    joint_b:
      multiplier: 1
      slow_mode_multiplier: 1
      invert: False
      xbox_index: 1
    joint_c:
      multiplier: -1
      slow_mode_multiplier: 0.6
      invert: False
      xbox_index: 4
    joint_de_pitch:
      multiplier: 0.5
      slow_mode_multiplier: 1
      invert: True
      xbox_index_left: 2
      xbox_index_right: 5
    joint_de_roll:
      multiplier: -0.5
      slow_mode_multiplier: 1
      invert: True
      xbox_index_left: 4
      xbox_index_right: 5
    allen_key:
      multiplier: 1
      slow_mode_multiplier: 1
      invert: False
      xbox_index: 7
    gripper:
      multiplier: 1
      slow_mode_multiplier: 1
      invert: True
      xbox_index: 7

  sa_controls:
    sa_x:
      multiplier: 1
      slow_mode_multiplier: 0.5
      xbox_index: 1
    sa_y:
      multiplier: -1
      slow_mode_multiplier: 0.5
      xbox_index: 0
    sa_z:
      multiplier: -1
      slow_mode_multiplier: 0.5
      xbox_index: 4
    sampler:
      multiplier: 1
      slow_mode_multiplier: 1.0
      xbox_index: 5
    sensor_actuator:
      multiplier: 1
      slow_mode_multiplier: 0.5
    cache:
      multiplier: 1
      xbox_index: 4

  drive_controls:
    forward_back:
      multiplier: 1
    left_right:
      # Can be disabled here since left_right axis sucks
      enabled: true
      multiplier: 1
    twist:
      multiplier: 0.7

  xbox_mappings:
    left_js_x: 0
    left_js_y: 1
    right_js_x: 3
    right_js_y: 4
    left_trigger: 2
    right_trigger: 5
    a: 0
    b: 1
    x: 2
    y: 3
    left_bumper: 4
    right_bumper: 5
    d_pad_x: 6
    d_pad_y: 7

  joystick_mappings:
    left_right: 1
    forward_back: 0
    twist: 2
    dampen: 3
    pan: 4
    tilt: 5

  mast_gimbal_power:
    rotation_pwr: 1.0
    up_down_pwr: 0.75

  # Thresholds in radians
  # Euclidean error is the norm of all the joint position errors
  euclidean_error_threshold: 3.14

  joint_error_thresholds:
    joint_a: 1.57
    joint_b: 1.57
    joint_c: 1.57
    joint_d: 1.57
    joint_e: 1.57

  # Mappings from site name to index in which values will be sent
  # for each site, mostly for heaters and which syringe servos we want to use
  site_mappings:
    A: 0
    B: 1
    C: 2

  echo_presets:
    blah: ["/tf", "/tf_static", "/rosout"]
    foo: ["/rosout", "/tf"]
    bar: ["/tf_static", "/rosout", "/tf"]

  ik_multipliers:
    x: 1
    y: 1
    z: 1