objects:
  - type: urdf
    name: rover
    uri: package://mrover/urdf/rover/rover.urdf.xacro
    transform:
      translation: [ 0, 0, 0 ]
      rotation: [ 0, 0, 0, 1 ]
  - type: urdf
    name: world
    uri: package://mrover/urdf/world/world.urdf.xacro
    transform:
      translation: [ 0, 0, 0 ]
      rotation: [ 0, 0, 0, 1 ]
