objects:
#  - type: urdf
#    name: rover
#    uri: package://mrover/urdf/rover/rover.urdf.xacro
#    translation: [ 0, 0, 0.5 ]
  - type: urdf
    name: world
    uri: package://mrover/urdf/world/world.urdf.xacro
#  - type: urdf
#    name: tag_0
#    uri: package://mrover/urdf/world/tag_0.urdf.xacro
#    translation: [ -3, -3, 0.7 ]
#  - type: urdf
#    name: tag_1
#    uri: package://mrover/urdf/world/tag_1.urdf.xacro
#    translation: [ 15, -14, 2.4 ]
