objects:
  - type: urdf
    name: rover
    uri: package://mrover/urdf/rover/rover.urdf.xacro
    translation: [-209, -154, 3]
  - type: urdf
    name: tag_1
    uri: package://mrover/urdf/world/tag_1.urdf.xacro
    translation: [ -236, -210, 1 ]
  - type: urdf
    name: world
    uri: package://mrover/urdf/world/mdrs.urdf.xacro
#  - type: urdf
#    name: lander
#    uri: package://mrover/urdf/world/lander.urdf.xacro
#    translation: [84.5, -45.89, -1.36]
