# All units are SI (meters, radians, seconds, etc.)

objects:
  - type: urdf
    name: rover
    uri: package://mrover/urdf/rover/rover.urdf.xacro
    translation: [ 0, 0, 0.5 ]
  - type: urdf
    name: world
    uri: package://mrover/urdf/world/world.urdf.xacro
  - type: urdf
    name: tag_0
    uri: package://mrover/urdf/world/tag_0.urdf.xacro
    translation: [ -2, -2, 0.7 ]
  - type: urdf
    name: tag_1
    uri: package://mrover/urdf/world/tag_1.urdf.xacro
    translation: [ 0.88, 10.53, 1.0 ]
  - type: urdf
    name: hammer
    uri: package://mrover/urdf/world/hammer.urdf.xacro
    translation: [ 5, 2, 0.7 ]
  - type: urdf
    name: bottle
    uri: package://mrover/urdf/world/bottle.urdf.xacro
    translation: [ -6.25, 10.5, 0.3 ]
  - type: urdf
    name: rock1
    uri: package://mrover/urdf/world/rock.urdf.xacro
    translation: [ 2, -2, 0.1 ]
  - type: urdf
    name: rock2
    uri: package://mrover/urdf/world/rock.urdf.xacro
    translation: [ 7, -6, 0.2 ]
  - type: urdf
    name: rock3
    uri: package://mrover/urdf/world/rock.urdf.xacro
    translation: [ 8, -10, 1 ]
  - type: urdf
    name: rock4
    uri: package://mrover/urdf/world/rock.urdf.xacro
    translation: [ 9, -2, 0.2 ]
  - type: urdf
    name: light2
    uri: package://mrover/urdf/world/light.urdf.xacro
    translation: [ 5.50, 7.33, 0.1 ]
  - type: urdf
    name: light3
    uri: package://mrover/urdf/world/light.urdf.xacro
    translation: [ 3.28, 9.92, 0.4 ]
