- name: Add Mesa PPA
  apt_repository:
    repo: ppa:kisak/kisak-mesa

- name: Add Mainline Kernel PPA
  apt_repository:
    repo: ppa:cappelikan/ppa

- name: Install APT Packages
  apt:
    cache_valid_time: 604800
    state: latest
    name:
      - mainline

- name: Upgrade APT Packages
  apt:
    upgrade: yes
