light_detector:
  upper_bound_h: 20
  upper_bound_s: 100
  upper_bound_v: 100
  lower_bound_h: 0
  lower_bound_s: 50
  lower_bound_v: 50
  spiral_search_radius: 50
  immediate_light_range: 2.5
  hit_increase: 5
  hit_decrease: 2
  hit_max: 100
  pub_threshold: 50
