light_detector:
  upper_bound_h: 5
  upper_bound_s: 101
  upper_bound_v: 101
  lower_bound_h: -1
  lower_bound_s: 90
  lower_bound_v: 50
  spiral_search_radius: 50
  immediate_light_range: 2.5
  hit_increase: 5
  hit_decrease: 2
  hit_max: 100
  pub_threshold: 50
