- name: Oh-My-Zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: /home/{{ ansible_user_id }}/.oh-my-zsh
    version: master

- name: Dotfiles
  synchronize:
    src: files/home
    dest: /home/{{ ansible_user_id }}
    recursive: true

- name: Jetson Stats
  become: True
  pip:
    name: jetson-stats

- name: Jetpack
  become: True
  apt:
    update_cache: true
    state: latest
    name:
      - nvidia-jetpack

# TODO: wait for jetpack 5.1.2 support
# - name: ZED SDK Download
#   get_url:
#     url: https://download.stereolabs.com/zedsdk/4.0/l4t35.1/jetsons
#     dest: /home/{{ ansible_user_id }}/Downloads/ZED_SDK_JP50_4.0.1.run
#     mode: 0755

# - name: ZED SDK Install
#   shell:
#     cmd: /home/{{ ansible_user_id }}/Downloads/ZED_SDK_JP50_4.0.1.run
#     creates: /usr/local/zed
#   become: True
#   become_user: root
#   become_method: sudo
