name: CI
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    container: umrover1/ros:latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'
          path: 'src'
      - run: . /opt/ros/noetic/setup.sh && catkin init
      - run: . /opt/ros/noetic/setup.sh && catkin build --cmake-args -DCMAKE_BUILD_TYPE=Release
      - run: . /opt/ros/noetic/setup.sh && . $GITHUB_WORKSPACE/devel/setup.sh && echo $LD_LIBRARY_PATH && catkin test
      # - run: cat $GITHUB_WORKSPACE/devel/setup.bash
      # - run: bash -c "source /opt/ros/noetic/setup.bash && source $GITHUB_WORKSPACE/devel/setup.bash && echo $LD_LIBRARY_PATH && catkin test"
