name: CI
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    container:
      image: umrover1/ros:latest
      options: --user root
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'
          path: 'src'
      - run: . /opt/ros/noetic/setup.sh && catkin init
      - run: . /opt/ros/noetic/setup.sh && catkin build --interleave-output --cmake-args -DCMAKE_BUILD_TYPE=Release
      - run: . /opt/ros/noetic/setup.sh && . $GITHUB_WORKSPACE/devel/setup.sh && catkin test -j1
