name: CI
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v1
      - uses: betwo/github-setup-catkin@master
        with:
          ros-version: "noetic"
          build-tool: "catkin_tools"
          workspace: "$GITHUB_WORKSPACE"
      - run: catkin build
