name: Style
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  code-style:
    name: Code Style Check
    runs-on: ubuntu-latest
    container: umrover1/ros:latest
    steps:
      - uses: actions/checkout@v3
      - name: Style check C++ and Python files
        run: ./style.sh
 