name: Style
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  formatting-check:
    name: Code Style Check
    runs-on: ubuntu-latest
    container: umrover1/ros:latest
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format style check for C/C++/Protobuf programs.
        run: ./style.sh
 